[package]
name = "oxc-miette-derive"
version = "1.0.1"
authors = ["Boshen", "Kat March√°n <kzm@zkat.tech>"]
edition = "2018"
license = "Apache-2.0"
description = "Derive macros for miette. Like `thiserror` for Diagnostics."
repository = "https://github.com/zkat/miette"

[lib]
proc-macro = true

[dependencies]
# Relaxed version so the user can decide which version to use.
proc-macro2 = "1"
quote = "1"
syn = "2"
